Android: Added line wrapping to slot name
ComputerScienceHouse/devin pull request #5
Opened 2023-02-22 17:05 UTC by atauln

Sometimes the name of the slots/what's in them can cut into the display for the credit amount for that slot. This effectively cuts it off at 15 characters and creates a newline if it can find a feasible spot.

2023-03-03 01:31 UTC, Mstrodl commented on lib/main.dart
> +          Text((name.length <= 15 || indexOfSpace == -1)
Different screen sizes will change this! Try to find a way to actually do text wrapping in Flutter

2023-03-03 01:32 UTC, Mstrodl approved these changes
Thanks for tackling this! Try to find a better way to do the line wrapping though... I bet flutter has a dingus

2023-03-08 03:48 UTC, Mstrodl requested changes
I'm stupid not sure why I clicked approve

2023-03-08 04:55 UTC, atauln reviewed
This should be a significantly better way to do it

2025-10-08 13:06 UTC, closed without merging